### ISSUE TITLE
estimate_timlag & estimate_dimension

### ISSUE THREAD

**Issue by terryjentsch** [amin-nejat/fcf#4]
I noticed that the estimate_timelag function in delay_embeding/estimate _timelag requires the transposed version of the data array e.g. (TxN) instead of (NxT) like everywhere else. 

Also the estimate_dimension function in delay_embedding/estimate dimension gives the following error for some datasets while functioning perfectly for others.

RayTaskError(ValueError): ray::_dim_fnn() (pid=9294, ip=10.231.22.24)
  File "/home/jentsch/FCF/delay_embedding/estimate_dimension.py", line 19, in _dim_fnn
    X_embedded = helpers.create_delay_vector(X,delay=time_delay,dim=dimension)
  File "/home/jentsch/FCF/delay_embedding/helpers.py", line 58, in create_delay_vector
    dvs[idx,:] = vec(sequence[idx:tShift+idx+1:delay,:])
ValueError: could not broadcast input array from shape (0,) into shape (372,)

**Comment by terryjentsch** [comment]
Furthermore, I think it would be beneficial if the save part of the ccm.connectivity() function would also save the timelag and dimension used.

**Comment by amin-nejat** [comment]
Dear Terry, thanks for your interest in my our code package. I just fixed both issues, now time (T) is the leading dimension of all functions. Please check it again and let me know if there are any issues. I also added delay and dimension to the saved properties of the ccm.connectivity function. Regarding the error you're getting, the use case of the false nearest neighbors method is on a per-dimension basis. Although you can input the function with the full multivariate signal (T,N) but you should be careful about the interpretation. Please give it another try and let me know if the error you're getting persists. Notice that the delay time needs to be smaller than the total number of time points in the signal.

**Comment by amin-nejat** [comment]
Dear Terry, thanks for your interest in my our code package. I just fixed both issues, now time (T) is the leading dimension of all functions. Please check it again and let me know if there are any issues. I also added delay and dimension to the saved properties of the ccm.connectivity function. Regarding the error you're getting, the use case of the false nearest neighbors method is on a per-dimension basis. Although you can input the function with the full multivariate signal (T,N) but you should be careful about the interpretation. Please give it another try and let me know if the error you're getting persists. Notice that the delay time needs to be smaller than the total number of time points in the signal.

**Comment by amin-nejat** [comment]
Resolved
